name: Drought
topics: 
    - Extreme events
    - Water
study-types:
  - directory: future-projections
  - name: Future Projections
  - description: projections of Earth's possible futures under climate change
  - ranking-files: 
    - land-abs-temp: 
        - direction: desc
    - land-abs-time:
        - direction: desc
    - pop-abs-temp:
        - direction: desc
    - pop-abs-time:
        - direction: desc
